# host_tune.py - apply the latency and power tuning host-precheck checks
#
# Copyright (C) 2026 Clyso Technologies Inc.
#
# This is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 2.1, as published by the Free Software
# Foundation.  See file COPYING.

"""Fix what host-precheck reports: power management, sysctls and tools.

Runtime settings (CPU governor and energy preference, deep C-states, PCIe
ASPM, NVMe APST, THP, NIC Energy-Efficient Ethernet) are written by one
generated shell script. The same script runs at boot from the
ceph-host-tune systemd unit, so what is applied now and what is applied
after a reboot cannot drift apart. I/O schedulers are set by a udev rule,
so hot-plugged disks get them too, and NUMA sysctls by a sysctl.d file.

Kernel command line arguments are only changed with cmdline=True: through
grubby on RHEL-family hosts, or else by adding them to GRUB_CMDLINE_LINUX in
/etc/default/grub and regenerating the grub configuration (Debian, Ubuntu,
SUSE). They take effect at the next reboot, which is left to the operator.

Missing tools that host-precheck and burnin use (smartmontools, nvme-cli,
ethtool, tuned, irqbalance, ipmitool on hosts with a BMC, stress-ng,
iperf3) are installed one by one with the distribution's package manager,
so one unavailable package does not stop the others; repositories are
never added. tuned and irqbalance are enabled.

The default is a dry run that shows what would change.
"""

import logging
import os
import re
import shutil

from glob import glob
from typing import Any, Dict, List, Optional

from .call_wrappers import call, CallVerbosity
from .context import CephadmContext
from .exceptions import Error
from .exe_utils import find_executable
from .file_utils import read_file, write_new
from . import host_hw
from .host_tuning import (
    CSTATE_MAX_LATENCY_US,
    TUNED_GOOD_PROFILES,
    SYSCTL_MANAGED,
    SYSCTL_RECOMMENDATIONS,
    SYS_CPU,
    SYS_NODE,
    THP_PATH,
    _bracketed,
    _cmdline,
    _cpu_model,
)

logger = logging.getLogger()

SCRIPT = '/usr/local/sbin/ceph-host-tune'
UNIT = 'ceph-host-tune.service'
UNIT_FILE = '/etc/systemd/system/' + UNIT
UDEV_RULE = '/etc/udev/rules.d/60-ceph-host-tune.rules'
# before cephadm's 90-ceph-<fsid>-*.conf, so an OSD's settings win
SYSCTL_FILE = '/etc/sysctl.d/80-ceph-host-tune.conf'
MODULES_FILE = '/etc/modules-load.d/ceph-host-tune.conf'
GRUB_DEFAULT = '/etc/default/grub'
GRUB_BACKUP = GRUB_DEFAULT + '.ceph-host-tune.bak'
MANAGED_FILES = [SCRIPT, UNIT_FILE, UDEV_RULE, SYSCTL_FILE, MODULES_FILE]

# (binary, package, what host-precheck or burnin uses it for); a package
# name may differ per package manager
TOOLS = [
    ('smartctl', 'smartmontools', 'disk health (SMART)'),
    ('nvme', 'nvme-cli', 'NVMe health'),
    ('ethtool', 'ethtool', 'NIC checks and tuning'),
    ('tuned-adm', 'tuned', 'performance profile'),
    ('irqbalance', 'irqbalance', 'spreads NIC interrupts over CPUs'),
    ('ipmitool', 'ipmitool', 'BMC event log and sensors'),
    ('stress-ng', 'stress-ng', 'burn-in CPU and memory stress'),
    ('iperf3', {'zypper': 'iperf'}, 'network burn-in'),
]
SERVICES = [('tuned', 'tuned-adm'), ('irqbalance', 'irqbalance')]
# an SMBIOS "IPMI device" entry: the host has a BMC
DMI_IPMI = '/sys/firmware/dmi/entries/38-0'
IPMI_MODULES = ['ipmi_si', 'ipmi_devintf']

BASE_CMDLINE = [
    'processor.max_cstate=1',
    'intel_idle.max_cstate=0',
    'pcie_aspm=off',
    'nvme_core.default_ps_max_latency_us=0',
]
TUNED_PROFILE = 'throughput-performance'

SCRIPT_BODY = """#!/bin/sh
# Generated by `cephadm host-tune`; run at boot by {unit}.
# Remove with `cephadm host-tune --remove`.

for f in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor; do
    echo performance > "$f" 2>/dev/null
done
for f in /sys/devices/system/cpu/cpu[0-9]*/cpufreq/energy_performance_preference; do
    echo performance > "$f" 2>/dev/null
done
# disable idle states that take longer than {max_lat}us to exit
for s in /sys/devices/system/cpu/cpu[0-9]*/cpuidle/state[0-9]*; do
    lat=$(cat "$s/latency" 2>/dev/null || echo 0)
    [ "$lat" -gt {max_lat} ] && echo 1 > "$s/disable" 2>/dev/null
done
echo performance > /sys/module/pcie_aspm/parameters/policy 2>/dev/null
for f in /sys/class/nvme/nvme*/power/pm_qos_latency_tolerance_us; do
    echo 0 > "$f" 2>/dev/null
done
if grep -q '\\[always\\]' {thp} 2>/dev/null; then
    echo madvise > {thp}
fi
if command -v ethtool >/dev/null; then
    for n in /sys/class/net/*; do
        [ -e "$n/device" ] && ethtool --set-eee "${{n##*/}}" eee off 2>/dev/null
    done
fi
{rings}exit 0
"""

# growing a NIC ring resets the link on many drivers, so this is opt-in
RINGS_BODY = """# grow NIC RX/TX rings to their maximum
if command -v ethtool >/dev/null; then
    for n in /sys/class/net/*; do
        [ -e "$n/device" ] || continue
        i=${n##*/}
        ethtool -g "$i" 2>/dev/null | awk '
            /maximums/ {m = 1; next}
            /Current/ {m = 2; next}
            /^RX:/ {if (m == 1) mr = $2; if (m == 2) cr = $2}
            /^TX:/ {if (m == 1) mt = $2; if (m == 2) ct = $2}
            END {if ((mr + 0 > cr + 0) || (mt + 0 > ct + 0)) print mr, mt}' |
        while read -r mr mt; do
            ethtool -G "$i" rx "$mr" tx "$mt" 2>/dev/null
        done
    done
fi
"""

UNIT_BODY = """# Generated by `cephadm host-tune`
[Unit]
Description=Ceph host latency and power tuning
After=tuned.service systemd-udevd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart={script}

[Install]
WantedBy=multi-user.target
"""

UDEV_BODY = """# Generated by `cephadm host-tune`
ACTION=="add|change", SUBSYSTEM=="block", ENV{DEVTYPE}=="disk", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="mq-deadline"
ACTION=="add|change", SUBSYSTEM=="block", ENV{DEVTYPE}=="disk", KERNEL=="nvme*|sd*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="none"
"""


def _read(path: str) -> Optional[str]:
    if not os.path.exists(path):
        return None
    v = read_file([path])
    return None if v == 'Unknown' else v


def _numa() -> bool:
    return len(glob(os.path.join(SYS_NODE, 'node[0-9]*'))) > 1


def _persisted_sysctls() -> Dict[str, str]:
    out = {}
    for line in (_read(SYSCTL_FILE) or '').splitlines():
        if '=' in line and not line.lstrip().startswith('#'):
            k, v = line.split('=', 1)
            out[k.strip()] = v.strip()
    return out


def sysctl_targets() -> List[Dict[str, str]]:
    """The recommended sysctls: current value and value to persist.

    Values only move toward the recommendation. Settings cephadm applies
    itself when it deploys an OSD are left to it. A setting stays persisted
    once host-tune has written it, even though it is now satisfied.
    """
    persisted = _persisted_sysctls()
    out = []
    for name, op, want, field, level, _why in SYSCTL_RECOMMENDATIONS:
        if level == SYSCTL_MANAGED:
            continue
        raw = _read('/proc/sys/' + name.replace('.', '/'))
        if raw is None:
            continue
        fields = raw.split()
        idx = field or 0
        try:
            cur = int(fields[idx])
        except (ValueError, IndexError):
            continue
        ok = cur >= want if op == '>=' else cur <= want
        if ok and name not in persisted:
            continue
        target = list(fields)
        if not ok:
            target[idx] = str(want)
        out.append(
            {
                'key': name,
                'current': ' '.join(fields),
                'target': persisted.get(name, ' '.join(target))
                if ok
                else ' '.join(target),
            }
        )
    if _numa():
        for name in ('vm.zone_reclaim_mode', 'kernel.numa_balancing'):
            raw = _read('/proc/sys/' + name.replace('.', '/'))
            if raw is not None:
                out.append({'key': name, 'current': raw, 'target': '0'})
    return out


def has_bmc() -> bool:
    return os.path.exists(DMI_IPMI)


def missing_tools() -> List[Dict[str, Any]]:
    out = []
    for binary, pkg, why in TOOLS:
        if binary == 'ipmitool' and not has_bmc():
            continue
        if not find_executable(binary):
            out.append({'binary': binary, 'package': pkg, 'why': why})
    return out


def _package_name(pkg: Any, packager: Any) -> str:
    if isinstance(pkg, str):
        return pkg
    kind = type(packager).__name__.lower()
    return pkg.get('zypper' if 'zypper' in kind else kind, 'iperf3')


def _eee_on(ctx: CephadmContext) -> List[str]:
    out = []
    for iface in host_hw.physical_nics():
        r = host_hw._run(ctx, ['ethtool', '--show-eee', iface])
        if r and not r[1] and re.search(r'EEE status:\s*enabled', r[0]):
            out.append(iface)
    return out


def _service_state(ctx: CephadmContext, svc: str) -> str:
    enabled, _, _ = call(
        ctx, ['systemctl', 'is-enabled', svc], verbosity=CallVerbosity.QUIET
    )
    active, _, _ = call(
        ctx, ['systemctl', 'is-active', svc], verbosity=CallVerbosity.QUIET
    )
    return '%s, %s' % (
        enabled.strip() or 'not installed',
        active.strip() or 'inactive',
    )


def _cmdline_args(iommu_off: bool, mitigations_off: bool) -> List[str]:
    args = list(BASE_CMDLINE)
    if iommu_off:
        if 'AMD' not in _cpu_model():
            raise Error('--iommu-off is only recommended for AMD EPYC hosts')
        args.append('amd_iommu=off')
    if mitigations_off:
        args.append('mitigations=off')
    return args


def _change(
    name: str, current: Any, target: Any, **kw: Any
) -> Dict[str, Any]:
    d = {'setting': name, 'current': current, 'target': target}
    d['change'] = current != target
    d.update(kw)
    return d


def plan(
    ctx: CephadmContext,
    cmdline: bool = False,
    iommu_off: bool = False,
    mitigations_off: bool = False,
    packages: bool = True,
    nic_rings: bool = False,
) -> List[Dict[str, Any]]:
    """What host-tune would change on this host."""
    want_args = _cmdline_args(iommu_off, mitigations_off) if cmdline else []
    out = []
    if packages:
        for t in missing_tools():
            pkg = t['package']
            out.append(
                _change(
                    'install '
                    + (pkg if isinstance(pkg, str) else t['binary']),
                    'missing',
                    'installed',
                    detail=t['why'],
                )
            )
    for svc, binary in SERVICES:
        if find_executable(binary) or (
            packages and any(t['binary'] == binary for t in missing_tools())
        ):
            out.append(
                _change(
                    'service ' + svc,
                    _service_state(ctx, svc),
                    'enabled, active',
                )
            )
    govs = sorted(
        {
            _read(p) or ''
            for p in glob(
                os.path.join(
                    SYS_CPU, 'cpu[0-9]*', 'cpufreq', 'scaling_governor'
                )
            )
        }
    )
    if govs:
        out.append(_change('cpu governor', ','.join(govs), 'performance'))
    epp = sorted(
        {
            _read(p) or ''
            for p in glob(
                os.path.join(
                    SYS_CPU,
                    'cpu[0-9]*',
                    'cpufreq',
                    'energy_performance_preference',
                )
            )
        }
    )
    if epp:
        out.append(
            _change('cpu energy preference', ','.join(epp), 'performance')
        )
    deep = []
    for st in sorted(
        glob(os.path.join(SYS_CPU, 'cpu0', 'cpuidle', 'state*'))
    ):
        try:
            lat = int(_read(os.path.join(st, 'latency')) or 0)
        except ValueError:
            continue
        if (
            lat > CSTATE_MAX_LATENCY_US
            and _read(os.path.join(st, 'disable')) != '1'
        ):
            deep.append(
                _read(os.path.join(st, 'name')) or os.path.basename(st)
            )
    if glob(os.path.join(SYS_CPU, 'cpu0', 'cpuidle', 'state*')):
        out.append(
            _change(
                'deep C-states',
                'enabled: ' + ','.join(deep) if deep else 'disabled',
                'disabled',
            )
        )
    aspm = _read('/sys/module/pcie_aspm/parameters/policy')
    if aspm:
        out.append(
            _change('PCIe ASPM policy', _bracketed(aspm), 'performance')
        )
    apst = [
        os.path.basename(os.path.dirname(os.path.dirname(p)))
        for p in glob(
            '/sys/class/nvme/nvme*/power/pm_qos_latency_tolerance_us'
        )
        if _read(p) not in ('0', None)
    ]
    if glob('/sys/class/nvme/nvme*'):
        out.append(
            _change(
                'NVMe APST',
                'enabled: ' + ','.join(apst) if apst else 'disabled',
                'disabled',
            )
        )
    thp = _read(THP_PATH)
    if thp:
        cur = _bracketed(thp)
        out.append(
            _change(
                'transparent hugepages',
                cur,
                'madvise' if cur == 'always' else cur,
            )
        )
    out.append(
        _change(
            'I/O schedulers (udev rule)',
            'installed' if os.path.exists(UDEV_RULE) else 'not installed',
            'installed',
            detail='mq-deadline for HDDs, none for flash',
        )
    )
    eee = _eee_on(ctx)
    if eee:
        out.append(
            _change(
                'NIC Energy-Efficient Ethernet', 'on: ' + ','.join(eee), 'off'
            )
        )
    if nic_rings:
        out.append(
            _change(
                'NIC rings',
                'as configured',
                'maximum',
                always=True,
                detail='resets the link of NICs whose rings grow',
            )
        )
    for t in sysctl_targets():
        out.append(_change('sysctl ' + t['key'], t['current'], t['target']))
    if has_bmc():
        out.append(
            _change(
                'IPMI kernel modules',
                'loaded'
                if host_hw.ipmi_available() or os.path.exists('/dev/ipmi0')
                else 'not loaded',
                'loaded',
                detail=' '.join(IPMI_MODULES),
            )
        )
    out.append(
        _change(
            'boot-time unit',
            'installed' if os.path.exists(UNIT_FILE) else 'not installed',
            'installed',
            detail=UNIT,
        )
    )
    active = _tuned_profile(ctx)
    tuned_coming = packages and any(
        t['binary'] == 'tuned-adm' for t in missing_tools()
    )
    if (find_executable('tuned-adm') or tuned_coming) and tuned_needs_profile(
        active
    ):
        out.append(
            _change('tuned profile', active or 'not installed', TUNED_PROFILE)
        )
    if cmdline:
        have = _cmdline()
        want = want_args
        missing = [a for a in want if a not in have]
        out.append(
            _change(
                'kernel command line',
                'missing %d argument(s)' % len(missing) if missing else 'set',
                'set',
                detail='%s (via %s)'
                % (
                    ' '.join(want),
                    {
                        'grubby': 'grubby',
                        'grub': GRUB_DEFAULT,
                    }.get(
                        cmdline_method() or '', 'nothing: add them by hand'
                    ),
                ),
                reboot=bool(missing),
            )
        )
    return out


def tuned_needs_profile(active: Optional[str]) -> bool:
    """Switch tuned only away from no or a non-performance stock profile."""
    if not active:
        return True
    if active in TUNED_GOOD_PROFILES:
        return False
    # an operator's own profile
    for d in ('/etc/tuned', '/etc/tuned/profiles'):
        if os.path.isdir(os.path.join(d, active)):
            return False
    return True


def _tuned_profile(ctx: CephadmContext) -> Optional[str]:
    if not find_executable('tuned-adm'):
        return None
    out, _, code = call(
        ctx, ['tuned-adm', 'active'], verbosity=CallVerbosity.QUIET
    )
    if code:
        return None
    for line in out.splitlines():
        if 'Current active profile:' in line:
            return line.split(':', 1)[1].strip()
    return None


def _write(path: str, body: str, mode: int) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with write_new(path, owner=None, perms=mode) as f:
        f.write(body)


def _run(ctx: CephadmContext, cmd: List[str]) -> Optional[str]:
    _, err, code = call(ctx, cmd, verbosity=CallVerbosity.QUIET)
    return None if code == 0 else (err.strip() or 'exit %d' % code)


def _install_tools(ctx: CephadmContext, step: Any) -> None:
    from .packagers import create_packager

    tools = missing_tools()
    if not tools:
        return
    try:
        packager = create_packager(ctx)
    except Exception as e:
        step('install packages', 'no package manager support: %s' % e)
        return
    if hasattr(packager, 'update'):
        try:
            packager.update()
        except Exception as e:
            logger.info('package list update failed: %s', e)
    for t in tools:
        name = _package_name(t['package'], packager)
        try:
            packager.install([name])
            err = None
        except Exception as e:
            lines = str(e).strip().splitlines()
            err = 'not installed: %s' % (
                lines[-1] if lines else type(e).__name__
            )
            if name == 'stress-ng' and 'Yum' in type(packager).__name__:
                err += ' (on EL it is in EPEL)'
        step('install %s (%s)' % (name, t['why']), err)


def apply(
    ctx: CephadmContext,
    cmdline: bool = False,
    iommu_off: bool = False,
    mitigations_off: bool = False,
    packages: bool = True,
    nic_rings: bool = False,
) -> List[Dict[str, Any]]:
    """Apply and persist the tuning; return what was done."""
    # validate before touching anything
    want_args = _cmdline_args(iommu_off, mitigations_off) if cmdline else []
    done = []

    def step(what: str, err: Optional[str]) -> None:
        done.append({'step': what, 'ok': err is None, 'error': err})

    if packages:
        _install_tools(ctx, step)
    for svc, binary in SERVICES:
        if find_executable(binary):
            step(
                'enable and start %s' % svc,
                _run(ctx, ['systemctl', 'enable', '--now', svc]),
            )
    if has_bmc():
        _write(
            MODULES_FILE,
            '# Generated by `cephadm host-tune`\n'
            + '\n'.join(IPMI_MODULES)
            + '\n',
            0o644,
        )
        step(
            'IPMI kernel modules (%s)' % MODULES_FILE,
            _run(ctx, ['modprobe', '-a'] + IPMI_MODULES),
        )

    # tuned would undo the governor and energy preference, so switch it to
    # a performance profile first and let the unit run after it
    active = _tuned_profile(ctx)
    if find_executable('tuned-adm') and tuned_needs_profile(active):
        step(
            'tuned profile %s' % TUNED_PROFILE,
            _run(ctx, ['tuned-adm', 'profile', TUNED_PROFILE]),
        )
    _write(SCRIPT, script_body(nic_rings), 0o755)
    step('runtime settings (%s)' % SCRIPT, _run(ctx, [SCRIPT]))
    _write(UNIT_FILE, UNIT_BODY.format(script=SCRIPT), 0o644)
    err = _run(ctx, ['systemctl', 'daemon-reload']) or _run(
        ctx, ['systemctl', 'enable', UNIT]
    )
    step('enable %s at boot' % UNIT, err)
    _write(UDEV_RULE, UDEV_BODY, 0o644)
    err = _run(ctx, ['udevadm', 'control', '--reload']) or _run(
        ctx,
        ['udevadm', 'trigger', '--subsystem-match=block', '--action=change'],
    )
    step('I/O schedulers (%s)' % UDEV_RULE, err)
    lines = ['%s = %s' % (t['key'], t['target']) for t in sysctl_targets()]
    if lines:
        _write(
            SYSCTL_FILE,
            '# Generated by `cephadm host-tune`\n' + '\n'.join(lines) + '\n',
            0o644,
        )
        step(
            'sysctls (%s)' % SYSCTL_FILE,
            _run(ctx, ['sysctl', '-p', SYSCTL_FILE]),
        )
    if want_args:
        missing = [a for a in want_args if a not in _cmdline()]
        method = cmdline_method()
        if not missing:
            step('kernel command line already set', None)
        elif method == 'grubby':
            err = _run(
                ctx,
                [
                    'grubby',
                    '--update-kernel=ALL',
                    '--args=' + ' '.join(missing),
                ],
            )
            step(
                'kernel command line: %s (reboot needed)' % ' '.join(missing),
                err,
            )
        elif method == 'grub':
            added = _edit_default_grub(missing)
            update = _grub_update_cmd()
            assert update is not None
            err = _run(ctx, update)
            step(
                'kernel command line: %s in %s, then %s (reboot needed)'
                % (' '.join(added) or 'nothing new', GRUB_DEFAULT, update[0]),
                err,
            )
        else:
            step(
                'kernel command line',
                'neither grubby nor %s with update-grub or grub-mkconfig '
                'found; add these arguments to the boot loader '
                'configuration by hand: %s'
                % (GRUB_DEFAULT, ' '.join(missing)),
            )
    return done


def script_body(nic_rings: bool) -> str:
    return SCRIPT_BODY.format(
        unit=UNIT,
        max_lat=CSTATE_MAX_LATENCY_US,
        thp=THP_PATH,
        rings=RINGS_BODY if nic_rings else '',
    )


def _grub_update_cmd() -> Optional[List[str]]:
    if find_executable('update-grub'):
        return ['update-grub']
    for tool, cfg in (
        ('grub2-mkconfig', '/boot/grub2/grub.cfg'),
        ('grub-mkconfig', '/boot/grub/grub.cfg'),
    ):
        if find_executable(tool) and os.path.exists(cfg):
            return [tool, '-o', cfg]
    return None


def cmdline_method() -> Optional[str]:
    """How kernel arguments can be changed on this host."""
    if find_executable('grubby'):
        return 'grubby'
    if os.path.exists(GRUB_DEFAULT) and _grub_update_cmd():
        return 'grub'
    return None


GRUB_CMDLINE_RE = re.compile(
    r'^GRUB_CMDLINE_LINUX=(?P<q>["\']?)(?P<args>.*?)(?P=q)[ \t]*$', re.M
)


def _edit_default_grub(args: List[str]) -> List[str]:
    """Add args to GRUB_CMDLINE_LINUX; return those that were not there."""
    with open(GRUB_DEFAULT) as f:
        text = f.read()
    if not os.path.exists(GRUB_BACKUP):
        shutil.copy2(GRUB_DEFAULT, GRUB_BACKUP)
    m = GRUB_CMDLINE_RE.search(text)
    have = m.group('args').split() if m else []
    added = [a for a in args if a not in have]
    if not added:
        return []
    line = 'GRUB_CMDLINE_LINUX="%s"' % ' '.join(have + added)
    if m:
        text = text[: m.start()] + line + text[m.end() :]
    else:
        text = text.rstrip('\n') + '\n' + line + '\n'
    with write_new(GRUB_DEFAULT, owner=None, perms=0o644) as f:
        f.write(text)
    return added


def remove(ctx: CephadmContext) -> List[Dict[str, Any]]:
    """Remove the persisted tuning. Runtime values stay until reboot."""
    done = []
    if os.path.exists(UNIT_FILE):
        err = _run(ctx, ['systemctl', 'disable', UNIT])
        done.append(
            {'step': 'disable ' + UNIT, 'ok': err is None, 'error': err}
        )
    for path in MANAGED_FILES:
        if os.path.exists(path):
            os.unlink(path)
            done.append({'step': 'remove ' + path, 'ok': True, 'error': None})
    _run(ctx, ['systemctl', 'daemon-reload'])
    _run(ctx, ['udevadm', 'control', '--reload'])
    done.append(
        {
            'step': 'installed packages and enabled tuned/irqbalance are left '
            'as they are',
            'ok': True,
            'error': None,
        }
    )
    all_args = ' '.join(BASE_CMDLINE + ['amd_iommu=off', 'mitigations=off'])
    method = cmdline_method()
    if method == 'grubby':
        how = 'grubby --update-kernel=ALL --remove-args="%s"' % all_args
    elif method == 'grub':
        how = 'remove them from GRUB_CMDLINE_LINUX in %s%s and run %s' % (
            GRUB_DEFAULT,
            ' (the original is %s)' % GRUB_BACKUP
            if os.path.exists(GRUB_BACKUP)
            else '',
            ' '.join(_grub_update_cmd() or []),
        )
    else:
        how = 'remove them from the boot loader configuration'
    done.append(
        {
            'step': 'kernel command line left as is (%s); to revert, %s'
            % (all_args, how),
            'ok': True,
            'error': None,
        }
    )
    return done


def format_plan(items: List[Dict[str, Any]]) -> str:
    rows = [('SETTING', 'CURRENT', 'TARGET', '')]
    for it in items:
        mark = 'change' if it['change'] or it.get('always') else ''
        if it.get('reboot'):
            mark += ' (reboot)'
        rows.append(
            (it['setting'], str(it['current']), str(it['target']), mark)
        )
    widths = [min(max(len(r[i]) for r in rows), 40) for i in range(3)]
    lines = []
    per_row: List[Optional[Dict[str, Any]]] = [None]
    per_row.extend(items)
    for r, it in zip(rows, per_row):
        lines.append(
            '  '.join(
                (c if len(c) <= w else c[: w - 3] + '...').ljust(w)
                for c, w in zip(r[:3], widths)
            )
            + '  '
            + r[3]
        )
        if it and it.get('detail'):
            lines.append('    ' + it['detail'])
    return '\n'.join(line.rstrip() for line in lines)


def format_done(done: List[Dict[str, Any]]) -> str:
    return '\n'.join(
        '%s %s%s'
        % (
            'OK  ' if d['ok'] else 'FAIL',
            d['step'],
            ': ' + d['error'] if d.get('error') else '',
        )
        for d in done
    )
